name: build-ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        dotnet-version: [ '6.0.x', '7.0.x', '8.0.x' ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore src/ManagedObjectSize.sln
    - name: Build
      run: dotnet build --no-restore --configuration ${{matrix.configuration}} src/ManagedObjectSize.sln
    - name: Test
      run: >
        dotnet test --no-build
        --configuration ${{matrix.configuration}}
        --verbosity normal
        --blame-crash
        --results-directory "TestResults-${{ matrix.configuration}}-${{ matrix.dotnet-version }}"
        src/ManagedObjectSize.Tests/ManagedObjectSize.Tests.csproj
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-testresults-${{ matrix.configuration}}-${{ matrix.dotnet-version }}
        path: TestResults-${{ matrix.configuration}}-${{ matrix.dotnet-version }}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}