name: Windows-CoreCLR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        dotnet-version: [ '6.0.x', '7.0.x', '8.0.x' ]
        os: [ 'windows-latest', 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore
      run: dotnet restore src/ManagedObjectSize.sln
    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }} src/ManagedObjectSize.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal src/ManagedObjectSize.Tests/ManagedObjectSize.Tests.csproj
